import type { Node, Edge } from "@xyflow/react";
import type { BoxNodeData } from "./BoxNode";
import { catalog } from "./boxCatalog";

// Build a lookup of box name → catalog entry
const catalogLookup = new Map(
  catalog.flatMap((section) => section.boxes.map((b) => [b.name, b])),
);

/**
 * Generates TypeScript code from the current diagram state.
 * Produces imperative pipe-style code matching the hand-written examples.
 */
export function generateCode(nodes: Node[], edges: Edge[]): string {
  const lines: string[] = [];
  const imports = new Set<string>();
  const nodeVars = new Map<string, string>();

  // Topological sort of nodes
  const sorted = topologicalSort(nodes, edges);

  // Track which boxes are needed for imports
  for (const node of sorted) {
    const data = node.data as unknown as BoxNodeData;
    imports.add(data.label);
  }

  // Generate import statement
  lines.push(`// Generated by Skein Studio`);
  lines.push(`// Import the boxes you need:`);
  lines.push(`// import { ${[...imports].join(", ")} } from "skein";`);
  lines.push(``);

  // Generate each node
  for (const node of sorted) {
    const data = node.data as unknown as BoxNodeData & { paramNames?: string[]; arrayInputs?: number[] };
    const catalogEntry = catalogLookup.get(data.label);
    const varName = toVarName(data.logicalId ?? data.label, nodeVars);
    nodeVars.set(node.id, varName);

    // Find inputs grouped by port index
    const inputEdges = edges.filter((e) => e.target === node.id);
    const portMap = new Map<number, string[]>();
    for (const e of inputEdges) {
      const portIndex = parseInt(e.targetHandle?.replace("in-", "") ?? "0");
      if (!portMap.has(portIndex)) portMap.set(portIndex, []);

      // Resolve the source variable — for multi-output nodes, reference the specific output
      const sourceNode = nodes.find((n) => n.id === e.source);
      const sourceData = sourceNode?.data as unknown as BoxNodeData | undefined;
      const sourceOutputIndex = parseInt(e.sourceHandle?.replace("out-", "") ?? "0");
      const baseVar = nodeVars.get(e.source) ?? "unknown";

      let sourceVar: string;
      if (sourceData && sourceData.resourceIds && sourceData.resourceIds.length > 1 && sourceOutputIndex > 0) {
        // Multi-output: use the specific output name
        const outputName = sourceData.resourceIds[sourceOutputIndex];
        sourceVar = outputName ? toVarName(outputName, new Map()) : baseVar;
      } else {
        sourceVar = baseVar;
      }

      portMap.get(portIndex)!.push(sourceVar);
    }

    const arrayInputs = new Set(data.arrayInputs ?? catalogEntry?.arrayInputs ?? []);
    const paramNames = data.paramNames ?? catalogEntry?.paramNames ?? data.inputNames ?? [];

    // Build argument list
    const args: string[] = [];
    for (let i = 0; i < data.inputCount; i++) {
      const vars = portMap.get(i) ?? [];
      if (vars.length === 0) {
        args.push(`/* ${paramNames[i] ?? `arg${i}`} */`);
      } else if (arrayInputs.has(i)) {
        args.push(`[${vars.join(", ")}]`);
      } else {
        args.push(vars[0]);
      }
    }

    // Find outputs: edges from this node
    const outputEdges = edges.filter((e) => e.source === node.id);
    const isUsedDownstream = outputEdges.length > 0;

    // Get user-configured values
    const config: Record<string, unknown> = (data as any).config ?? {};
    const logicalId = (config.logicalId as string) || data.logicalId || data.label;
    const hasConfig = Object.keys(config).some((k) => k !== "logicalId");

    if (data.isGenerator && data.inputCount === 0) {
      // Constructor: no inputs, just config
      const propsStr = serializeConfig(config, ["logicalId"]);
      if (isUsedDownstream) {
        lines.push(`const ${varName} = ${data.label}("${logicalId}", ${propsStr || "{ /* props */ }"});`);
      } else {
        lines.push(`${data.label}("${logicalId}", ${propsStr || "{ /* props */ }"});`);
      }
    } else if (data.inputCount === 1 && data.outputCount === 1 && !data.logicalId && !hasConfig) {
      // Single-input single-output transformer (no config)
      if (isUsedDownstream) {
        lines.push(`const ${varName} = ${data.label}(${args[0]});`);
      } else {
        lines.push(`${data.label}(${args[0]});`);
      }
    } else if (data.logicalId || config.logicalId || hasConfig) {
      // Named pattern box or box with config: use object syntax
      // Combine wire args and config into a single props object
      const propsObj: Record<string, string> = {};

      // Add wire connections (resource inputs only)
      const catalogInputs = catalogEntry?.inputs ?? [];
      for (let i = 0; i < args.length; i++) {
        const inputType = catalogInputs[i];
        if (inputType && RESOURCE_TYPES.has(inputType)) {
          propsObj[paramNames[i] ?? `arg${i}`] = args[i];
        }
      }

      // Add config values
      const configStr = serializeConfig(config, ["logicalId"]);

      // Build the final props string
      const wireStr = Object.entries(propsObj).map(([k, v]) => `${k}: ${v}`).join(", ");
      const allProps = [wireStr, configStr ? `...${configStr}` : ""].filter(Boolean).join(", ");

      if (isUsedDownstream) {
        const destructured = data.resourceIds?.slice(0, 2).map((r) => toVarName(r, new Map())).join(", ");
        lines.push(`const { ${destructured || varName} } = ${data.label}("${logicalId}", { ${allProps || "/* props */"} });`);
      } else {
        lines.push(`${data.label}("${logicalId}", { ${allProps || "/* props */"} });`);
      }
    } else if (args.some((a) => !a.startsWith("/*"))) {
      // Positional arguments (no config, no logicalId)
      if (isUsedDownstream) {
        lines.push(`const ${varName} = ${data.label}(${args.join(", ")});`);
      } else {
        lines.push(`${data.label}(${args.join(", ")});`);
      }
    } else {
      // Nothing connected or configured
      if (isUsedDownstream) {
        lines.push(`const ${varName} = ${data.label}(/* connect inputs */);`);
      } else {
        lines.push(`${data.label}(/* connect inputs */);`);
      }
    }
  }

  return lines.join("\n");
}

const RESOURCE_TYPES = new Set([
  "Table", "Queue", "Topic", "Function", "Function[]", "VPC",
  "Subnets", "Subnet", "Bucket", "StateMachine", "Alarm", "Asset",
]);

function serializeConfig(config: Record<string, unknown>, exclude: string[]): string {
  const excludeSet = new Set(exclude);
  const filtered: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(config)) {
    if (excludeSet.has(k)) continue;
    if (v === "" || v === null || v === undefined) continue;
    filtered[k] = v;
  }
  if (Object.keys(filtered).length === 0) return "";
  return serializeValue(filtered);
}

function serializeValue(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "string") return `"${value}"`;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map(serializeValue);
    return `[${items.join(", ")}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== "" && v !== null && v !== undefined)
      .map(([k, v]) => `${k}: ${serializeValue(v)}`);
    if (entries.length === 0) return "{}";
    return `{ ${entries.join(", ")} }`;
  }
  return String(value);
}

function toVarName(name: string, existing: Map<string, string>): string {
  // camelCase the name
  let base = name[0].toLowerCase() + name.slice(1);
  base = base.replace(/[^a-zA-Z0-9]/g, "");

  // Deduplicate
  const usedNames = new Set(existing.values());
  if (!usedNames.has(base)) return base;
  let i = 2;
  while (usedNames.has(`${base}${i}`)) i++;
  return `${base}${i}`;
}

function topologicalSort(nodes: Node[], edges: Edge[]): Node[] {
  const nodeMap = new Map(nodes.map((n) => [n.id, n]));
  const incoming = new Map<string, Set<string>>();
  const nodeIds = new Set(nodes.map((n) => n.id));

  for (const node of nodes) {
    incoming.set(node.id, new Set());
  }
  for (const edge of edges) {
    if (nodeIds.has(edge.source) && nodeIds.has(edge.target)) {
      incoming.get(edge.target)?.add(edge.source);
    }
  }

  const result: Node[] = [];
  const queue: string[] = [];

  for (const [id, deps] of incoming) {
    if (deps.size === 0) queue.push(id);
  }

  while (queue.length > 0) {
    const current = queue.shift()!;
    const node = nodeMap.get(current);
    if (node) result.push(node);

    for (const edge of edges) {
      if (edge.source === current && nodeIds.has(edge.target)) {
        incoming.get(edge.target)?.delete(current);
        if (incoming.get(edge.target)?.size === 0) {
          queue.push(edge.target);
        }
      }
    }
  }

  // Add any remaining nodes (disconnected)
  for (const node of nodes) {
    if (!result.includes(node)) result.push(node);
  }

  return result;
}
