import { mkStateMachine } from "../generated/stepfunctions.js";
import type { StateMachine } from "../generated/stepfunctions.js";
import type { LambdaFunction } from "../generated/lambda.js";
import { mkRole, mkPolicy } from "../generated/iam.js";
import type { Role } from "../generated/iam.js";
import { ref, deriveId } from "../runtime/resource.js";
import { box } from "../runtime/box.js";

// === Step definition types ===

type Retry = {
  errorEquals: string[];
  intervalSeconds?: number;
  maxAttempts?: number;
  backoffRate?: number;
};

type Catch = {
  errorEquals: string[];
  next: string;
  resultPath?: string;
};

export type LambdaStep = {
  name: string;
  fn: LambdaFunction;
  resultPath?: string;
  outputPath?: string;
  retry?: Retry[];
  catch?: Catch[];
};

export type ChoiceRule = {
  variable: string;
  comparison: string;
  value: unknown;
  next: string;
};

export type ChoiceStep = {
  name: string;
  choices: ChoiceRule[];
  default?: string;
};

export type ParallelStep = {
  name: string;
  branches: Step[][];
  resultPath?: string;
  retry?: Retry[];
  catch?: Catch[];
};

export type MapStep = {
  name: string;
  itemsPath: string;
  iterator: Step[];
  maxConcurrency?: number;
  resultPath?: string;
  retry?: Retry[];
  catch?: Catch[];
};

export type WaitStep = {
  name: string;
} & (
  | { seconds: number }
  | { timestamp: string }
  | { secondsPath: string }
  | { timestampPath: string }
);

export type PassStep = {
  name: string;
  result?: unknown;
  resultPath?: string;
  parameters?: Record<string, unknown>;
};

export type SucceedStep = {
  name: string;
  succeed: true;
};

export type FailStep = {
  name: string;
  error: string;
  cause: string;
};

export type Step =
  | LambdaStep
  | ChoiceStep
  | ParallelStep
  | MapStep
  | WaitStep
  | PassStep
  | SucceedStep
  | FailStep;

function stepKind(step: Step): string {
  if ("fn" in step) return "lambda";
  if ("choices" in step) return "choice";
  if ("branches" in step) return "parallel";
  if ("iterator" in step) return "map";
  if ("seconds" in step || "timestamp" in step || "secondsPath" in step || "timestampPath" in step) return "wait";
  if ("succeed" in step) return "succeed";
  if ("error" in step && "cause" in step) return "fail";
  if ("result" in step || "parameters" in step) return "pass";
  return "pass";
}

function collectLambdas(steps: Step[]): LambdaFunction[] {
  const fns: LambdaFunction[] = [];
  const seen = new Set<string>();

  function visit(s: Step) {
    if ("fn" in s && !seen.has(s.fn.logicalId)) {
      seen.add(s.fn.logicalId);
      fns.push(s.fn);
    }
    if ("branches" in s) {
      for (const branch of s.branches) branch.forEach(visit);
    }
    if ("iterator" in s) {
      s.iterator.forEach(visit);
    }
  }

  steps.forEach(visit);
  return fns;
}

// === Mid-level boxes ===

/**
 * Creates an IAM role for a Step Functions state machine with permission
 * to invoke the specified Lambda functions.
 */
export const stateMachineRole = box(
  "stateMachineRole",
  (logicalId: string, lambdas: LambdaFunction[]): Role => {
    const role = mkRole(`${logicalId}Role`, {
      assumeRolePolicyDocument: {
        Version: "2012-10-17",
        Statement: [{
          Effect: "Allow",
          Principal: { Service: "states.amazonaws.com" },
          Action: "sts:AssumeRole",
        }],
      },
    });

    if (lambdas.length > 0) {
      mkPolicy(`${logicalId}InvokePolicy`, {
        policyName: `${logicalId}InvokePolicy`,
        policyDocument: {
          Version: "2012-10-17",
          Statement: [{
            Effect: "Allow",
            Action: "lambda:InvokeFunction",
            Resource: lambdas.map(fn => fn.arn),
          }],
        },
        roles: [ref(role)],
      });
    }

    return role;
  },
);

/**
 * Builds an Amazon States Language definition from a list of steps.
 *
 * Steps are chained sequentially by default (each step's Next points to the
 * following step in the array). Choice, Succeed, and Fail steps manage their
 * own transitions explicitly.
 *
 * Supports: Task (Lambda), Choice, Parallel, Map, Wait, Pass, Succeed, Fail.
 */
export function buildDefinition(steps: Step[]): Record<string, unknown> {
  const states: Record<string, unknown> = {};

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];
    const isLast = i === steps.length - 1;
    const nextState = isLast ? undefined : steps[i + 1].name;

    states[step.name] = buildState(step, nextState, isLast);
  }

  return {
    Comment: "Generated by Skein",
    StartAt: steps[0].name,
    States: states,
  };
}

function buildState(step: Step, nextState: string | undefined, isLast: boolean): Record<string, unknown> {
  const kind = stepKind(step);

  switch (kind) {
    case "lambda": return buildLambdaState(step as LambdaStep, nextState, isLast);
    case "choice": return buildChoiceState(step as ChoiceStep, nextState);
    case "parallel": return buildParallelState(step as ParallelStep, nextState, isLast);
    case "map": return buildMapState(step as MapStep, nextState, isLast);
    case "wait": return buildWaitState(step as WaitStep, nextState, isLast);
    case "pass": return buildPassState(step as PassStep, nextState, isLast);
    case "succeed": return { Type: "Succeed" };
    case "fail": return { Type: "Fail", Error: (step as FailStep).error, Cause: (step as FailStep).cause };
    default: return { Type: "Pass", ...transition(nextState, isLast) };
  }
}

function transition(nextState: string | undefined, isLast: boolean): Record<string, unknown> {
  return isLast ? { End: true } : { Next: nextState };
}

function toAslRetry(retries: Retry[]): unknown[] {
  return retries.map(r => ({
    ErrorEquals: r.errorEquals,
    ...(r.intervalSeconds !== undefined && { IntervalSeconds: r.intervalSeconds }),
    ...(r.maxAttempts !== undefined && { MaxAttempts: r.maxAttempts }),
    ...(r.backoffRate !== undefined && { BackoffRate: r.backoffRate }),
  }));
}

function toAslCatch(catches: Catch[]): unknown[] {
  return catches.map(c => ({
    ErrorEquals: c.errorEquals,
    Next: c.next,
    ...(c.resultPath !== undefined && { ResultPath: c.resultPath }),
  }));
}

function buildLambdaState(step: LambdaStep, nextState: string | undefined, isLast: boolean): Record<string, unknown> {
  const state: Record<string, unknown> = {
    Type: "Task",
    Resource: "arn:aws:states:::lambda:invoke",
    Parameters: {
      FunctionName: step.fn.arn,
      "Payload.$": "$",
    },
    ResultPath: step.resultPath ?? "$",
    OutputPath: step.outputPath ?? "$.Payload",
    ...transition(nextState, isLast),
  };

  if (step.retry) state.Retry = toAslRetry(step.retry);
  if (step.catch) state.Catch = toAslCatch(step.catch);

  return state;
}

function buildChoiceState(step: ChoiceStep, nextState: string | undefined): Record<string, unknown> {
  const choices = step.choices.map(c => ({
    Variable: c.variable,
    [c.comparison]: c.value,
    Next: c.next,
  }));

  const state: Record<string, unknown> = { Type: "Choice", Choices: choices };
  if (step.default) state.Default = step.default;
  else if (nextState) state.Default = nextState;

  return state;
}

function buildParallelState(step: ParallelStep, nextState: string | undefined, isLast: boolean): Record<string, unknown> {
  const branches = step.branches.map(branch => buildDefinition(branch));

  const state: Record<string, unknown> = {
    Type: "Parallel",
    Branches: branches,
    ...transition(nextState, isLast),
  };

  if (step.resultPath) state.ResultPath = step.resultPath;
  if (step.retry) state.Retry = toAslRetry(step.retry);
  if (step.catch) state.Catch = toAslCatch(step.catch);

  return state;
}

function buildMapState(step: MapStep, nextState: string | undefined, isLast: boolean): Record<string, unknown> {
  const iterator = buildDefinition(step.iterator);

  const state: Record<string, unknown> = {
    Type: "Map",
    ItemsPath: step.itemsPath,
    ItemProcessor: iterator,
    ...transition(nextState, isLast),
  };

  if (step.maxConcurrency !== undefined) state.MaxConcurrency = step.maxConcurrency;
  if (step.resultPath) state.ResultPath = step.resultPath;
  if (step.retry) state.Retry = toAslRetry(step.retry);
  if (step.catch) state.Catch = toAslCatch(step.catch);

  return state;
}

function buildWaitState(step: WaitStep, nextState: string | undefined, isLast: boolean): Record<string, unknown> {
  const state: Record<string, unknown> = {
    Type: "Wait",
    ...transition(nextState, isLast),
  };

  if ("seconds" in step) state.Seconds = step.seconds;
  else if ("timestamp" in step) state.Timestamp = step.timestamp;
  else if ("secondsPath" in step) state.SecondsPath = step.secondsPath;
  else if ("timestampPath" in step) state.TimestampPath = step.timestampPath;

  return state;
}

function buildPassState(step: PassStep, nextState: string | undefined, isLast: boolean): Record<string, unknown> {
  const state: Record<string, unknown> = {
    Type: "Pass",
    ...transition(nextState, isLast),
  };

  if (step.result !== undefined) state.Result = step.result;
  if (step.resultPath) state.ResultPath = step.resultPath;
  if (step.parameters) state.Parameters = step.parameters;

  return state;
}

// === High-level box ===

export type StepFunctionsPipelineProps = {
  steps: Step[];
  type?: "STANDARD" | "EXPRESS";
};

export type StepFunctionsPipeline = {
  readonly stateMachine: StateMachine;
  readonly role: Role;
};

/**
 * Creates a Step Functions state machine from a declarative list of steps.
 *
 * Supported step types:
 * - **LambdaStep** — invokes a Lambda function with the state as payload
 * - **ChoiceStep** — branches based on conditions on the state
 * - **ParallelStep** — runs multiple branches concurrently
 * - **MapStep** — iterates a sub-workflow over an array in the state
 * - **WaitStep** — pauses for a duration or until a timestamp
 * - **PassStep** — injects or transforms data without side effects
 * - **SucceedStep** / **FailStep** — explicit terminal states
 *
 * Steps are chained sequentially by default. Choice, Succeed, and Fail
 * manage their own transitions. The state machine role is automatically
 * granted lambda:InvokeFunction on all Lambda functions found in the step
 * tree (including inside Parallel branches and Map iterators).
 */
export const stepFunctionsPipeline = box(
  "stepFunctionsPipeline",
  (logicalId: string, props: StepFunctionsPipelineProps): StepFunctionsPipeline => {
    const { steps, type = "STANDARD" } = props;

    const lambdas = collectLambdas(steps);
    const role = stateMachineRole(logicalId, lambdas);
    const definition = buildDefinition(steps);

    const stateMachine = mkStateMachine(logicalId, {
      roleArn: role,
      stateMachineType: type,
      definition,
    });

    return { stateMachine, role };
  },
);